// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3i5U7u5-ugP-c7xIWCh7VH93F2rbOvCY',
    appId: '1:968247810330:web:adcad475ccc42b4328f4a3',
    messagingSenderId: '968247810330',
    projectId: 'rutamove',
    authDomain: 'rutamove.firebaseapp.com',
    storageBucket: 'rutamove.firebasestorage.app',
    measurementId: 'G-3C64161P51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7u_OLrGizNF8id1FVkGgIz-oQhtBUIo',
    appId: '1:968247810330:android:c7b2defed7a8899f28f4a3',
    messagingSenderId: '968247810330',
    projectId: 'rutamove',
    storageBucket: 'rutamove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBElWpZn1PriIbLRYP0pfCDFOcZzi5O8JE',
    appId: '1:968247810330:ios:5a52290930451ad028f4a3',
    messagingSenderId: '968247810330',
    projectId: 'rutamove',
    storageBucket: 'rutamove.firebasestorage.app',
    iosClientId: '968247810330-2j2g9v5o2vc7h6ksshv5p9p2iev9b1m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBElWpZn1PriIbLRYP0pfCDFOcZzi5O8JE',
    appId: '1:968247810330:ios:4cade2ea81628be028f4a3',
    messagingSenderId: '968247810330',
    projectId: 'rutamove',
    storageBucket: 'rutamove.firebasestorage.app',
    iosClientId: '968247810330-1lfihfvin4os3p2lru94r9u7mjfm06si.apps.googleusercontent.com',
    iosBundleId: 'com.RutaMove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3i5U7u5-ugP-c7xIWCh7VH93F2rbOvCY',
    appId: '1:968247810330:web:2b750f7e44c4508f28f4a3',
    messagingSenderId: '968247810330',
    projectId: 'rutamove',
    authDomain: 'rutamove.firebaseapp.com',
    storageBucket: 'rutamove.firebasestorage.app',
    measurementId: 'G-Y9PDR4T6ZZ',
  );
}
